/* =====================================================================
   NexaCommerce  -  04_SeedData.sql
   Reference data. Every block is guarded so the script is re-runnable.
   Users, products and order history are generated by the application
   on first run (passwords need PBKDF2 hashing done in C#).
   ===================================================================== */
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.Roles)
INSERT INTO dbo.Roles (Name, Description) VALUES
 ('Admin',    'Full access including users, settings and audit log'),
 ('Manager',  'Catalog, inventory, orders, reports and intelligence'),
 ('Staff',    'Day-to-day order processing and stock handling'),
 ('Customer', 'Storefront shopper');

IF NOT EXISTS (SELECT 1 FROM dbo.Settings)
INSERT INTO dbo.Settings (SettingKey, SettingValue, Description) VALUES
 ('StoreName',             'NexaCommerce',  'Name shown in the header and on invoices'),
 ('StoreTagline',          'Everyday goods, stocked by data', 'Short line under the store name'),
 ('StoreEmail',            'support@nexacommerce.com', 'Support e-mail printed on invoices'),
 ('StorePhone',            '+880 1700-000000', 'Support phone printed on invoices'),
 ('StoreAddress',          'Karwan Bazar, Dhaka-1215, Bangladesh', 'Address printed on invoices'),
 ('ShippingFee',           '60',    'Flat delivery charge per order'),
 ('FreeShippingThreshold', '2000',  'Orders at or above this subtotal ship free (0 disables)'),
 ('LowStockAlerts',        'true',  'Raise a notification when stock drops to its reorder level'),
 ('RiskHighThreshold',     '60',    'Risk score at or above which an order is flagged High'),
 ('RiskMediumThreshold',   '30',    'Risk score at or above which an order is flagged Medium'),
 ('ForecastHorizonDays',   '30',    'Days ahead the demand forecast projects'),
 ('ForecastHistoryDays',   '120',   'Days of sales history used to fit the forecast'),
 ('ServiceLevelZ',         '1.65',  'Safety-stock z value (1.65 = 95% service level)'),
 ('OrderingCost',          '500',   'Fixed cost per purchase order, used in EOQ'),
 ('HoldingCostRate',       '0.20',  'Annual holding cost as a fraction of unit cost, used in EOQ'),
 ('BasketMinSupportCount', '3',     'Minimum co-purchase count for a product-pair rule');

IF NOT EXISTS (SELECT 1 FROM dbo.Warehouses)
INSERT INTO dbo.Warehouses (Name, Location, Capacity) VALUES
 ('Dhaka Central',  'Tejgaon Industrial Area, Dhaka', 25000),
 ('Chattogram Hub', 'Agrabad, Chattogram', 12000),
 ('Sylhet Depot',   'Zindabazar, Sylhet', 5000);

IF NOT EXISTS (SELECT 1 FROM dbo.Categories)
INSERT INTO dbo.Categories (Name, Slug, Description, Icon) VALUES
 ('Electronics',            'electronics',  'Audio, TVs and smart home devices', 'bi-tv'),
 ('Computers & Accessories','computers',    'Laptops, peripherals and storage', 'bi-laptop'),
 ('Mobile & Gadgets',       'mobile',       'Phones, wearables and charging gear', 'bi-phone'),
 ('Home & Kitchen',         'home-kitchen', 'Cookware, appliances and pantry', 'bi-cup-hot'),
 ('Fashion',                'fashion',      'Clothing, bags and footwear', 'bi-bag'),
 ('Books & Stationery',     'books',        'Books, notebooks and desk supplies', 'bi-book'),
 ('Sports & Fitness',       'sports',       'Training gear and outdoor equipment', 'bi-bicycle'),
 ('Beauty & Personal Care', 'beauty',       'Skin, hair and grooming', 'bi-flower1');

IF NOT EXISTS (SELECT 1 FROM dbo.Brands)
INSERT INTO dbo.Brands (Name, Description) VALUES
 ('NovaTech',    'Consumer electronics and computing'),
 ('Zenith',      'Mobile devices and accessories'),
 ('HomeCraft',   'Kitchen and home essentials'),
 ('UrbanThread', 'Everyday fashion'),
 ('PageTurner',  'Books and stationery'),
 ('PeakFit',     'Sports and fitness'),
 ('Lumina',      'Beauty and personal care'),
 ('Generic',     'Unbranded goods');

IF NOT EXISTS (SELECT 1 FROM dbo.Suppliers)
INSERT INTO dbo.Suppliers (Name, ContactPerson, Email, Phone, Address, LeadTimeDays) VALUES
 ('Bengal Tech Distributors', 'Rafiq Ahmed',   'orders@bengaltech.example',  '+880 1711-111111', 'Elephant Road, Dhaka', 7),
 ('Delta Mobile Imports',     'Nusrat Jahan',  'supply@deltamobile.example', '+880 1722-222222', 'Bashundhara City, Dhaka', 10),
 ('HomeLine Wholesale',       'Kamal Hossain', 'sales@homeline.example',     '+880 1733-333333', 'Chawkbazar, Chattogram', 5),
 ('Threadworks Garments',     'Sadia Islam',   'b2b@threadworks.example',    '+880 1744-444444', 'Ashulia, Savar', 14),
 ('Paper & Ink Traders',      'Tanvir Rahman', 'hello@paperink.example',     '+880 1755-555555', 'Banglabazar, Dhaka', 4);

IF NOT EXISTS (SELECT 1 FROM dbo.Coupons)
INSERT INTO dbo.Coupons (Code, Description, DiscountType, Value, MinOrderAmount, MaxUses, StartsAt, EndsAt) VALUES
 ('WELCOME10', '10% off your first order',       'Percent', 10,  0,    NULL, DATEADD(DAY,-200,SYSDATETIME()), DATEADD(YEAR,1,SYSDATETIME())),
 ('FLAT500',   'Tk 500 off orders over Tk 5000', 'Fixed',   500, 5000, 500,  DATEADD(DAY,-200,SYSDATETIME()), DATEADD(YEAR,1,SYSDATETIME())),
 ('RESEARCH15','15% off - research pilot users', 'Percent', 15,  1000, 100,  DATEADD(DAY,-30,SYSDATETIME()),  DATEADD(MONTH,6,SYSDATETIME()));
